name: build and release
# on:
#   workflow_run:
#     workflows: ["merge to build"]
#     types:
#       - completed

on:
  workflow_call:
    secrets:
      token:
        required: true


jobs:
  build:
    runs-on: ubuntu-latest
    name: build and release the project
    steps:
      - uses: actions/checkout@v3
        with:
          ref: build

      - name: build the project
        run: echo build the project
      
