on:
  push:
    tags:
      - 'v*'
jobs:
  create_release:
    name: Create release
    runs-on: ubuntu-latest
    # Note this. We are going to use that in further jobs.
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
          body: CHANGELOG.md

  build:
    runs-on: ubuntu-latest
    needs: create_release
    steps:
      - uses: actions/checkout@v3
      - name: Check cmake
        run: cmake --version
      - name: Configure
        run: cmake -S. -Bbuild -DCMAKE_BUILD_TYPE="Release" -DCMAKE_INSTALL_PREFIX=install
      - name: Build
        run: cmake --build build --config "Release" --target all -v
      - name: List
        run: ls build
      - name: Run The app
        run: build/TestCpp

      - name: version
        id: version
        run: echo ::set-output name=version::${GITHUB_REF/refs\/tags\//}
        
      - name: upload artifacts
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: ./build/TestCpp${{ matrix.asset_name_suffix }}
          asset_name: TestCppExec_${{ runner.os }}_${{ steps.version.outputs.version }}${{ matrix.asset_name_suffix }}
          asset_content_type: application/octet-stream
  
