on:
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            asset_name_suffix: ''
            asset_content_type: application/octet-stream
          - os: windows-latest
            asset_name_suffix: .exe
            asset_content_type: application/octet-stream
          - os: macOS-latest
            asset_name_suffix: ''
            asset_content_type: application/octet-stream
    steps:
      - uses: actions/checkout@v3
      - name: Check cmake
        run: cmake --version
      - name: Configure
        run: cmake -S. -Bbuild -DCMAKE_BUILD_TYPE="Release" -DCMAKE_INSTALL_PREFIX=install
      - name: Build
        run: cmake --build build --config "Release" --target all -v
      - name: List
        run: ls build
      - name: Run The app
        run: build/TestCpp

      - name: version
        run: echo "::set-output name=version::test_version"
        id: version
        with:
          - VERSION: ${{ github.ref }}
      - name: release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: ${{ github.ref }}
          tag_name: ${{ github.ref }}
          body_path: CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: upload linux artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/TestCpp${{ matrix.asset_name_suffix }}
          asset_name: TestCppExec_${{ runner.os }}_${{ steps.version.outputs.VERSION }}${{ matrix.asset_name_suffix }}
          asset_content_type: application/octet-stream