name: merge build and release
on:
  workflow_dispatch:


jobs:
  merge_to_build_brench:
    name: merge develop brench to build brench
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          ref: develop

      - name: Merge develop -> build
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: develop
          target_branch: build
          github_token: ${{ github.token }}




  build_and_release:
    needs: merge_to_build_brench

    runs-on: ubuntu-latest
    name: build and release the project
    steps:
      
      - name: checkout
        uses: actions/checkout@v3
        with:
          ref: build
        
      - name: fetch version
        id: version
        run: |
          echo "::set-output name=major::$(python3 ver.py get MAJOR)"
          echo "::set-output name=minor::$(python3 ver.py get MINOR)"
          python3 ver.py increase PATCH
          echo "::set-output name=patch::$(python3 ver.py get PATCH)"

      - name: configure project
        run: echo configure project
      
      - name: list variables
        run: echo ${{ steps.version.outputs.major }}.${{ steps.version.outputs.minor }}.${{ steps.version.outputs.patch }}

      - name: build the project
        run: echo build the project




  update_main_brench_version:
    needs: build_and_release
    name: update main branch version
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          ref: develop

      - name: Merge build -> main
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: build
          target_branch: main
          github_token: ${{ github.token }}
