name: merge to build
on:
  workflow_dispatch:
jobs:

  build:
    runs-on: ubuntu-latest
    name: merge to build job
    steps:
      - uses: actions/checkout@v3
        with:
          ref: develop

      - name: Merge development -> staging
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: develop
          target_branch: build
          github_token: ${{ github.token }}
      
