name: merge build brench to main


on:
  workflow_call:
jobs:
  merge_to_master:
    name: merge build brench to main brench
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: build

      - name: Merge build -> main
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: develop
          target_branch: main
          github_token: ${{ github.token }}
        
